### ISSUE TITLE
Status do vitinho :D

### ISSUE THREAD

**Issue by downzin-pamonha** [ictor226/ictor226#1]
<img width=100% src="https://capsule-render.vercel.app/api?type=waving&color=670B71&height=120&section-header"/>
 
<div align="center"
<a href="https://git.io/typing-svg"><img src="https://readme-typing-svg.herokuapp.com?font=Proggy+Fonts&weight=200&size=23&pause=1000&color=670B71&center=true&vCenter=true&width=500&lines=HELLO+my+name+is+victor+huggo;i'am+17+years+old;And+i'am+From+brazil" alt="Typing SVG" /></a></div>
 
 
***
[![Ashutosh's github activity graph](https://github-readme-activity-graph.vercel.app/graph?username=ictor226&bg_color=000000&color=670B71&line=3D0843&point=fff&area=true&hide_border=true)](https://github.com/ashutosh00710/github-readme-activity-graph)

## Conhecimentos:
![JAVASCRIPT](https://img.shields.io/badge/JAVASCRIPT-321435?style=for-the-badge&logo=JAVASCRIPT&logoColor=YELLOW)&nbsp;
<img align="right" height="110" alt="coding-time" src="https://media.tenor.com/mcpNuaDanYwAAAAj/duck-ducky.gif">
![HTML5](https://img.shields.io/badge/HTML5-321435?style=for-the-badge&logo=html5&logoColor=orange)&nbsp;

## Ferramentas:
 
![GITHUB](https://img.shields.io/badge/GITHUB-321435?style=for-the-badge&logo=github&logoColor=white)&nbsp;
![PHOTOSHOP](https://img.shields.io/badge/PHOTOSHOP-321435?style=for-the-badge&logo=Adobe%20Photoshop&logoColor=blue)&nbsp;
![CANVA](https://img.shields.io/badge/CANVA-321435.svg?&style=for-the-badge&logo=Canva&logoColor=cyan)&nbsp;
![FIGMA](https://img.shields.io/badge/FIGMA-321435?style=for-the-badge&logo=figma&logoColor=orange)&nbsp;
![ARDUINO](https://img.shields.io/badge/ARDUINO-321435?style=for-the-badge&logo=arduino&logoColor=green)&nbsp;
![OPERA_GX](https://img.shields.io/badge/OPERA_GX-321435?style=for-the-badge&logo=Opera&logoColor=red)&nbsp;
![Visual Studio](https://img.shields.io/badge/-Visual%20Studio-321435?style=for-the-badge&logo=visual-studio&logoColor=C8A2C8&labelColor=0D1117)&nbsp;
![Visual Studio Code](https://img.shields.io/badge/-Visual%20Studio%20Code-321435?style=for-the-badge&logo=visual-studio&logoColor=1E90FF&labelColor=0D1117)&nbsp;
 
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GustavoSobrera20/GustavoSobrera20/output/github-contribution-grid-snake-dark.svg"> <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GustavoSobrera20/GustavoSobrera20/output/github-contribution-grid-snake.svg"> <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/GustavoSobrera20/GustavoSobrera20/output/github-contribution-grid-snake.svg"> </picture>
 
 
## Estudando no Momento:
 
![CSS](https://img.shields.io/badge/CSS3-321435?style=for-the-badge&logo=css3&logoColor=skyblue)&nbsp;
![C#](https://img.shields.io/badge/C%23-321435?style=for-the-badge&logo=c-sharp&logoColor=darkgreen)&nbsp;
 
<p align="centre"><b>Visitors Count</b></p> 
<p align="center"><img align="center" src="https://visit-counter.vercel.app/counter.png?page=https%3A%2F%2Fgithub.com%ictor226&s=50&c=670B71&bg=00000000&no=7&ff=digi&tb=Visits%3A++&ta=" /></p> 
<br>

## Status:
<div align="center">
     <img height="150" src="https://github-readme-stats.vercel.app/api?username=ictor226&show_icons=true&theme=synthwave&include_all_commits=true&count_private=true" alt="GitHub Stats"/>
      <img height="150" src="https://github-readme-stats.vercel.app/api/top-langs/?username=ictor226&layout=compact&langs_count=7&theme=synthwave" alt="Top Languages"/></div>

**Comment by ictor226** [comment]
Vlww MN :)
